<div class="card-header">Dashboard</div>
<div class="card-body">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->views->listUsers as $user): ?>
                <tr>
                    <th scope="row"><?= $user['id']?></th>
                    <td><?= $user['name']?></td>
                    <td><?= $user['email']?></td>
                </tr>
            <?php endforeach?>
        </tbody>
    </table>
</div>