<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>Framework</title>
    <link rel="shortcut icon" href="img/favicon.ico" />

    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.css">

    <!-- Fa Icons Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Styles CSS  -->
    <link rel="stylesheet" href="css/layout.css">
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="">Dashboard</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
            <a class="nav-link" id="btn-exit" href="">Sair</a>
            </li>
        </ul>
    </nav>'
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="/dashboard">
                                <i class="fa fa-home"></i>
                                Inicio
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/user">
                                <i class="fa fa-user-circle"></i>
                                Usuarios
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/item">
                                <i class="fas fa-box-open"></i>
                                Itens
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/saller">
                                <i class="fas fa-user-tie"></i>
                                Vendedores
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/customer">
                                <i class="fa fa-id-card"></i>
                                Clientes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/order">
                                <i class="fa fa-tasks"></i>
                                Venda
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/payment">
                                <i class="fas fa-money-check-alt"></i>
                                Formas de Pagamento
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">

                            <?php if($this->view->message) :?>
                                <div class="alert alert-<?= $this->view->type ?>" role="alert">
                                    <?= $this->view->message ?>
                                </div>
                            <?php endif; ?>

                            <?=$this->content()?>

                            <?php if(isset($this->view->pagination)) :?>
                                <?=$this->pagination()?>
                            <?php endif; ?>

                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"> </script>

    <!-- Fas Icons -->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <!-- jQuery -->
    <script src="js/jQuery.js"></script>
</body>
</html>