<nav>
    <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" href="<?=$this->view->pagination->first?>">Primeira</a></li>
        <li class="page-item"><a class="page-link" href="<?=$this->view->pagination->previous?>">Anterior</a></li>
        <li class="page-item"><a class="page-link" href="<?=$this->view->pagination->previous?>"><?=$this->view->pagination->page -1 ?></a></li>
        <li class="page-item"><a class="page-link" href="<?=$this->view->pagination->current?>"><?=$this->view->pagination->page?></a></li>
        <li class="page-item"><a class="page-link" href="<?=$this->view->pagination->next?>"><?=$this->view->pagination->page +1 ?></a></li>
        <li class="page-item"><a class="page-link" href="<?=$this->view->pagination->next?>">Próximo</a></li>
        <li class="page-item"><a class="page-link" href="<?=$this->view->pagination->last?>">Ultimo</a></li>
    </ul>
</nav>