<div class="d-flex card-header">
    <h4 class="mr-auto p-2">Usuarios</h4>
    <div class="p-2"><button type="button" class="btn btn-info">Adicionar</button></div>
</div>

<div class="card-body">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->views->users as $user): ?>
                <tr>
                    <th scope="row"><?= $user['id']?></th>
                    <td><?= $user['name']?></td>
                    <td><?= $user['email']?></td>
                </tr>
            <?php endforeach?>
        </tbody>
    </table>
</div>